#!/usr/bin/env python
# Expects ~/.jira.cfg to to contain:
#
# [whistle]
# server: https://whistle.atlassian.net
# username: snoopy
# password: r3d8@r0n

import argparse
import logging

from collections import defaultdict
try:
    from jira.client import JIRA
except ImportError as e:
    print >> sys.stderr, "Jira not found; try `pip install jira`."

import ConfigParser, os, sys

class Config(object):
    
    def __init__(self, config_path=None, scope=None):
        
        self._server = dict()
        
        if config_path is not None:
            config = ConfigParser.SafeConfigParser()
            files = config.read(os.path.expanduser(config_path))
            if len(files) == 0:
                raise Exception(sys.stderr, "{0} not found; exiting.".format(config_path))

            if scope is None:
                scope = config.get('defaults', 'scope')
                
            if scope is None:
                raise Exception("No scope provided.")
            
            # print >> sys.stderr, "Using scope: {}".format(scope)
            
            try:
                self._server['username'] = config.get("{}.server".format(scope), 'username')
                self._server['password'] = config.get("{}.server".format(scope), 'password')
                self._server['server'] = config.get("{}.server".format(scope), 'server')
                self._filters = defaultdict(lambda: None, config.items("{}.filters".format(scope)))
                
            except ConfigParser.NoSectionError as e:
                print >> sys.stderr, e
                raise Exception("No {}.server section found; check your ~/.jira.cfg.".format(scope))
                
    @property
    def server(self):
        return self._server
        
    @property
    def filters(self):
        return self._filters
    
class Client(object):
    
    def __init__(self, config):

        self._jira = JIRA(
            basic_auth=(config.server['username'], config.server['password']),
            options={'server': config.server['server']}
        )
        
    def query(self, jql=None, filter_id=None, filter=None, fields=["summary", "issuetype"]):
        
        """
        Filter issues.
        :param: jql The JQL query to use. If provided, takes precedence.
        :param: filter A filter object from which to extract jql
        :param: filter_id the ID of a saved filter.
        :param: An array of additional fields to grab.
        
        If multiple non-nil parameters are provided, they're considered in the order
        listed above.
        """
        
        ljql = self.get_jql(jql=jql, filter_id=filter_id, filter=filter)
        if ljql is None:
            return None
            
        ret = self._jira.search_issues(ljql, fields=",".join(fields))
        return ret
        
    def get_jql(self, jql=None, filter_id=None, filter=None):
        ljql = jql
        
        if ljql is None:
            if filter is not None:
                ljql = filter.jql
            
        if ljql is None:
            if filter_id is not None:
                filter = self._jira.filter(filter_id)
                if filter is not None:
                    ljql = filter.jql
                    
        return ljql
        
        print >> sys.stderr, ljql
        
        

class markdown_formatter(object):
    def __call__(self, issues=[]):
        return ("\n".join(["* [{0}]({1}) ({2}): {3}".format(i.key, i.self, i.fields.issuetype.name, i.fields.summary) for i in issues]))
        
    @property
    def fields(self):
        return ["summary", "issuetype"]
  
def config(args):
    """
    Run a filter (specified by name, filterid, or JQL).
    """
    
    pass

def list_issues(args):
    """
    List issues, according to filter criteria.
    """
    
    print >> sys.stderr, repr(args)
    
    config = Config(args.config, scope=args.scope)
    formatter = markdown_formatter()
    client = Client(config)
    
    jql = args.jql
    filter_id = args.filterid
    if filter_id is None:
        filter_id = config.filters[args.filtername]
    
    ljql = client.get_jql(jql=jql, filter_id=filter_id)

    if ljql is None:
        return

    if args.dump:
        print ljql
        return

    print formatter(Client(config).query(jql=ljql, fields=formatter.fields))
        
if __name__ == "__main__":

    parser = argparse.ArgumentParser(prog = "jt")
    parser.add_argument("-s", "--scope", help="The scope against which to execute commands. Defaults to value of 'scope' in config 'defaults' section.")
    parser.add_argument("-c", "--config", default="~/.jira.cfg", help="Path to config file; defaults to ~/.jira.cfg.")
    subparsers = parser.add_subparsers(help="Subcommands")
    
    # jt is -f FILTERNAME
    # jt is -F FILTERID
    # jt is -j JQL
    # jt is -f FILTERNAME -d
    
    ls_parser = subparsers.add_parser("is", help="List issues")
    ls_filter_group = ls_parser.add_mutually_exclusive_group()
    ls_filter_group.add_argument("-F", "--filterid", type=str, help="The filter ID to use")
    ls_filter_group.add_argument("-f", "--filtername", type=str, help="The filter preset (configured in .jira.cfg) to use")
    ls_filter_group.add_argument("-j", "--jql", type=str, help="JQL to use. For example, 'jt is -j \'project = SW AND status = Started AND component = \"Tagg iOS\"\'")
    ls_parser.add_argument("-d", "--dump", action="store_true", help="Dump JQL and exit.")
    ls_parser.set_defaults(func=list_issues)
    
    # jt config 
    

    # parser.add_argument("-s", "--scope", type=str, help="The scope to use, otherwise defaults to whatever is in [default]")
    
    args = parser.parse_args()
    
    # logging.basicConfig(level=logging.FATAL-(10*max(0, min(5, args.verbosity)))
    
    args.func(args)
